# Generated by Django 3.0.7 on 2020-09-12 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierproductcostview',
            options={'managed': False},
        ),
    ]
