# Generated by Django 3.0.7 on 2020-09-12 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200912_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierproductcostview',
            options={},
        ),
    ]
